import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const mainFont = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tools W/O Bullshxt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
